name: sales_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  date_picker_timeline: ^1.2.5
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_localizations:
    sdk: flutter 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
